FROM node:16

WORKDIR /app

COPY ./backend/package*.json package*.json
COPY ./backend/.env .env 

RUN npm ci

RUN npm i @nestjs/cli -g

COPY . .

EXPOSE 3001

RUN apt-get update -y && apt-get install -y openssl

RUN npm install @prisma/client prisma
