FROM node:18

WORKDIR /app

COPY package*.json ./
COPY .env ./

RUN npm ci

RUN npm i @nestjs/cli -g

COPY . .

EXPOSE 3001

RUN apt-get update -y && apt-get install -y openssl

RUN npm install @prisma/client prisma

RUN npm run build

CMD ["npm", "run", "start"]
