services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
