export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TEMP_USER_REPOSITORY = 'TEMP_USER_REPOSITORY';
export const COUPLE_REPOSITORY = 'COUPLE_REPOSITORY';
export const REQUEST_REPOSITORY = 'REQUEST_REPOSITORY';
